{
  "formatVersion": "1.1",
  "component": {
    "url": "../../FetchMoodle/2026.2.2/FetchMoodle-2026.2.2.module",
    "group": "lib.fetchmoodle",
    "module": "FetchMoodle",
    "version": "2026.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "FetchMoodle-jvm-2026.2.2.jar",
          "url": "FetchMoodle-jvm-2026.2.2.jar",
          "size": 203501,
          "sha512": "4f019a81c0ab1ff4d9f28797c43843dd283ab3af07cfff93d9bd0dbb26dea099d599a4ad72bb906875050379f5174e2a71dcdb5c1fa09bb2cb26ca30b82b75c0",
          "sha256": "b53e2c4113a567b1c883208976534297e6a64352ab4611123b02a3dd62ab0d87",
          "sha1": "6b68a7e61d895e2737b74cf1754658ac44a7b701",
          "md5": "9bae27c530a9fe0ef1cf67989ffb09c0"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.fleeksoft.ksoup",
          "module": "ksoup",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "FetchMoodle-jvm-2026.2.2.jar",
          "url": "FetchMoodle-jvm-2026.2.2.jar",
          "size": 203501,
          "sha512": "4f019a81c0ab1ff4d9f28797c43843dd283ab3af07cfff93d9bd0dbb26dea099d599a4ad72bb906875050379f5174e2a71dcdb5c1fa09bb2cb26ca30b82b75c0",
          "sha256": "b53e2c4113a567b1c883208976534297e6a64352ab4611123b02a3dd62ab0d87",
          "sha1": "6b68a7e61d895e2737b74cf1754658ac44a7b701",
          "md5": "9bae27c530a9fe0ef1cf67989ffb09c0"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "FetchMoodle-jvm-2026.2.2-sources.jar",
          "url": "FetchMoodle-jvm-2026.2.2-sources.jar",
          "size": 10947,
          "sha512": "72e1a4425544a1e0e8a53bb929dcf6b542c52cc51c2291b3222209b8a498ca7c2ebb2d98f76cf62e7279b07f7e3f9e34e641c4c2d404537633646f118c327b58",
          "sha256": "5ac21483c57f132efcd273bdaed36b6a3b152ed04740598b7146091f350c1296",
          "sha1": "31d9e4411c6b942b415673db863f4dd23ef08e44",
          "md5": "4dbcc660706c0a38eb8b9430556f3728"
        }
      ]
    }
  ]
}
