{
  "formatVersion": "1.1",
  "component": {
    "group": "me.earzuchan.hiro",
    "module": "skia",
    "version": "1.6.6-alpha-cmp1.11.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko-android",
          "version": {
            "requires": "0.144.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "skia-1.6.6-alpha-cmp1.11.1.aar",
          "url": "skia-1.6.6-alpha-cmp1.11.1.aar",
          "size": 6078402,
          "sha512": "618b0f1f5ab5c97aa930c140e81b06c2e273e48d3d6c36ad7f3bd620494f91d4cfd51a57c7d773b36ade7cea06a3b423e5da4855be924928d87a14d38685fe29",
          "sha256": "25a58c0494335c51c80118c2f311e9f972d2b24c95a5f0770b011b4d2f78fda0",
          "sha1": "57fe4887e1ffaaf1105d9d44351505faf2bc9a55",
          "md5": "9df3341873ed74b0ad2d776b29258072"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko-android",
          "version": {
            "requires": "0.144.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "skia-1.6.6-alpha-cmp1.11.1.aar",
          "url": "skia-1.6.6-alpha-cmp1.11.1.aar",
          "size": 6078402,
          "sha512": "618b0f1f5ab5c97aa930c140e81b06c2e273e48d3d6c36ad7f3bd620494f91d4cfd51a57c7d773b36ade7cea06a3b423e5da4855be924928d87a14d38685fe29",
          "sha256": "25a58c0494335c51c80118c2f311e9f972d2b24c95a5f0770b011b4d2f78fda0",
          "sha1": "57fe4887e1ffaaf1105d9d44351505faf2bc9a55",
          "md5": "9df3341873ed74b0ad2d776b29258072"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "skia-1.6.6-alpha-cmp1.11.1-sources.jar",
          "url": "skia-1.6.6-alpha-cmp1.11.1-sources.jar",
          "size": 14431,
          "sha512": "4ae39995e67d37b46d0157f6c439bc9fd5e98893e0154edfaf627c25e3da7da1676d06acfb01e90c22417e76b59d15edf496e82088f244b2242bb36eda1f68b1",
          "sha256": "5b952477cd982a9afd057cee34df2db150a03a5b4796ec3240fa5a4b20119e01",
          "sha1": "932e71b5d9377660fe8978802352bfd4b124f2c7",
          "md5": "90bb8d7631c3b26fe6ccf06a58466604"
        }
      ]
    }
  ]
}
