{
  "formatVersion": "1.1",
  "component": {
    "group": "me.earzuchan.hiro",
    "module": "material3",
    "version": "1.6.6-alpha-cmp1.11.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.earzuchan.hiro",
          "module": "compose",
          "version": {
            "requires": "1.6.6-alpha-cmp1.11.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "material3-1.6.6-alpha-cmp1.11.1.aar",
          "url": "material3-1.6.6-alpha-cmp1.11.1.aar",
          "size": 4474993,
          "sha512": "bba36e68f8f6f330388e10f6468b637a9bdb7e4a42e26fab4ae18f8119d3ea07888ebbc87cbce37049ac6fa529cf69fd9f12df28e1d934857c96235904f513ec",
          "sha256": "27e9c34433e896ea7a1e6d44eb4bfc921354f1e07a632e86bf889e9b565d4f73",
          "sha1": "f21f8c375eb520933ad878dc44dd9b0e5232de74",
          "md5": "87c12608df5539a9592337c495c74054"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.earzuchan.hiro",
          "module": "compose",
          "version": {
            "requires": "1.6.6-alpha-cmp1.11.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "material3-1.6.6-alpha-cmp1.11.1.aar",
          "url": "material3-1.6.6-alpha-cmp1.11.1.aar",
          "size": 4474993,
          "sha512": "bba36e68f8f6f330388e10f6468b637a9bdb7e4a42e26fab4ae18f8119d3ea07888ebbc87cbce37049ac6fa529cf69fd9f12df28e1d934857c96235904f513ec",
          "sha256": "27e9c34433e896ea7a1e6d44eb4bfc921354f1e07a632e86bf889e9b565d4f73",
          "sha1": "f21f8c375eb520933ad878dc44dd9b0e5232de74",
          "md5": "87c12608df5539a9592337c495c74054"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "material3-1.6.6-alpha-cmp1.11.1-sources.jar",
          "url": "material3-1.6.6-alpha-cmp1.11.1-sources.jar",
          "size": 9434,
          "sha512": "4b271736dfa078c654eadccb48a645ed0db464d1fa8581f9634cd50e2247ae981045c17fff9fd9de6de085c004ba70d5b1d2e1f1e6e911d471fb619d4db9b55e",
          "sha256": "a75457ce28eba8b2f5dfe9694024dc2632e2b7a95e5c180067d9457d19d89a82",
          "sha1": "cced3f05a93aa09e3951f2519c60db70decd7d7e",
          "md5": "250685745dc7a1eeba306d3c033b28ef"
        }
      ]
    }
  ]
}
