{
  "formatVersion": "1.1",
  "component": {
    "group": "lib.fetchmoodle",
    "module": "FetchMoodle",
    "version": "2026.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.fleeksoft.ksoup",
          "module": "ksoup",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "FetchMoodle-metadata-2026.2.2.jar",
          "url": "FetchMoodle-2026.2.2.jar",
          "size": 9818,
          "sha512": "5e3eabfde93ff33d4bca595dccb7354a859b7e96f0e1835a1e54b4c6ff45b695c33ae16ca17f17534fb923314636072c1c7ef4daf2d37487085bf139d9573c24",
          "sha256": "142309b6c2e4ff6fa8bbb42705f31508f49ca468800cdb6d2da9cfa42cc93b92",
          "sha1": "5df1a40c2ae71058901b5c7ed4c5c79175cbfc31",
          "md5": "652c37793425ab735cc1115169df6ffa"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "FetchMoodle-kotlin-2026.2.2-sources.jar",
          "url": "FetchMoodle-2026.2.2-sources.jar",
          "size": 10947,
          "sha512": "72e1a4425544a1e0e8a53bb929dcf6b542c52cc51c2291b3222209b8a498ca7c2ebb2d98f76cf62e7279b07f7e3f9e34e641c4c2d404537633646f118c327b58",
          "sha256": "5ac21483c57f132efcd273bdaed36b6a3b152ed04740598b7146091f350c1296",
          "sha1": "31d9e4411c6b942b415673db863f4dd23ef08e44",
          "md5": "4dbcc660706c0a38eb8b9430556f3728"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../FetchMoodle-iosarm64/2026.2.2/FetchMoodle-iosarm64-2026.2.2.module",
        "group": "lib.fetchmoodle",
        "module": "FetchMoodle-iosarm64",
        "version": "2026.2.2"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../FetchMoodle-iosarm64/2026.2.2/FetchMoodle-iosarm64-2026.2.2.module",
        "group": "lib.fetchmoodle",
        "module": "FetchMoodle-iosarm64",
        "version": "2026.2.2"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../FetchMoodle-iosarm64/2026.2.2/FetchMoodle-iosarm64-2026.2.2.module",
        "group": "lib.fetchmoodle",
        "module": "FetchMoodle-iosarm64",
        "version": "2026.2.2"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../FetchMoodle-iossimulatorarm64/2026.2.2/FetchMoodle-iossimulatorarm64-2026.2.2.module",
        "group": "lib.fetchmoodle",
        "module": "FetchMoodle-iossimulatorarm64",
        "version": "2026.2.2"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../FetchMoodle-iossimulatorarm64/2026.2.2/FetchMoodle-iossimulatorarm64-2026.2.2.module",
        "group": "lib.fetchmoodle",
        "module": "FetchMoodle-iossimulatorarm64",
        "version": "2026.2.2"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../FetchMoodle-iossimulatorarm64/2026.2.2/FetchMoodle-iossimulatorarm64-2026.2.2.module",
        "group": "lib.fetchmoodle",
        "module": "FetchMoodle-iossimulatorarm64",
        "version": "2026.2.2"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../FetchMoodle-iosx64/2026.2.2/FetchMoodle-iosx64-2026.2.2.module",
        "group": "lib.fetchmoodle",
        "module": "FetchMoodle-iosx64",
        "version": "2026.2.2"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../FetchMoodle-iosx64/2026.2.2/FetchMoodle-iosx64-2026.2.2.module",
        "group": "lib.fetchmoodle",
        "module": "FetchMoodle-iosx64",
        "version": "2026.2.2"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../FetchMoodle-iosx64/2026.2.2/FetchMoodle-iosx64-2026.2.2.module",
        "group": "lib.fetchmoodle",
        "module": "FetchMoodle-iosx64",
        "version": "2026.2.2"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../FetchMoodle-jvm/2026.2.2/FetchMoodle-jvm-2026.2.2.module",
        "group": "lib.fetchmoodle",
        "module": "FetchMoodle-jvm",
        "version": "2026.2.2"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../FetchMoodle-jvm/2026.2.2/FetchMoodle-jvm-2026.2.2.module",
        "group": "lib.fetchmoodle",
        "module": "FetchMoodle-jvm",
        "version": "2026.2.2"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../FetchMoodle-jvm/2026.2.2/FetchMoodle-jvm-2026.2.2.module",
        "group": "lib.fetchmoodle",
        "module": "FetchMoodle-jvm",
        "version": "2026.2.2"
      }
    }
  ]
}
