{
  "formatVersion": "1.1",
  "component": {
    "group": "me.earzuchan.hiro.gradleplugin",
    "module": "hiro-gradle-plugin",
    "version": "1.7.0-alpha-cmp1.11.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "hiro-gradle-plugin-1.7.0-alpha-cmp1.11.1.jar",
          "url": "hiro-gradle-plugin-1.7.0-alpha-cmp1.11.1.jar",
          "size": 65934,
          "sha512": "57a2c926f53e4434419916a40bfa26a76d3a582116f6cdff4e22621c1f02167c6614229be2f13f9216842d8f5e27ab152f2cec45ea244f62df596be78e57e4f5",
          "sha256": "c330ce19961cb233311ff505b637860efc30294b295b44aebab0b93836643c9c",
          "sha1": "d3d3a1c6ae7e016c5d977a89e66f6613b9fee3f0",
          "md5": "287aea6e069d17c9e820adc030ce3778"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "hiro-gradle-plugin-1.7.0-alpha-cmp1.11.1.jar",
          "url": "hiro-gradle-plugin-1.7.0-alpha-cmp1.11.1.jar",
          "size": 65934,
          "sha512": "57a2c926f53e4434419916a40bfa26a76d3a582116f6cdff4e22621c1f02167c6614229be2f13f9216842d8f5e27ab152f2cec45ea244f62df596be78e57e4f5",
          "sha256": "c330ce19961cb233311ff505b637860efc30294b295b44aebab0b93836643c9c",
          "sha1": "d3d3a1c6ae7e016c5d977a89e66f6613b9fee3f0",
          "md5": "287aea6e069d17c9e820adc030ce3778"
        }
      ]
    }
  ]
}
