{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/2026.2.3/core-2026.2.3.module",
    "group": "lib.fetchmoodle",
    "module": "core",
    "version": "2026.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "FetchMoodle-jvm-2026.2.3.jar",
          "url": "FetchMoodle-jvm-2026.2.3.jar",
          "size": 204539,
          "sha512": "186541b1e2b32e9b729766310f07a19429fca1e3b8b18a2bc2707b6d58a3d9355dfb4f2e3cb279ac2a2737b110cfa5095392b918279ccafda02c320b3e1e92cc",
          "sha256": "646de913574bf1aa89896350989f060f3fafc367324675f605cd982e70d4a55b",
          "sha1": "236c8ddc65c0a34b205ea722813a9909ca403db4",
          "md5": "5a262901d1f3c22fb3283663b3794059"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "com.fleeksoft.ksoup",
          "module": "ksoup",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "FetchMoodle-jvm-2026.2.3.jar",
          "url": "FetchMoodle-jvm-2026.2.3.jar",
          "size": 204539,
          "sha512": "186541b1e2b32e9b729766310f07a19429fca1e3b8b18a2bc2707b6d58a3d9355dfb4f2e3cb279ac2a2737b110cfa5095392b918279ccafda02c320b3e1e92cc",
          "sha256": "646de913574bf1aa89896350989f060f3fafc367324675f605cd982e70d4a55b",
          "sha1": "236c8ddc65c0a34b205ea722813a9909ca403db4",
          "md5": "5a262901d1f3c22fb3283663b3794059"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "FetchMoodle-jvm-2026.2.3-sources.jar",
          "url": "FetchMoodle-jvm-2026.2.3-sources.jar",
          "size": 11555,
          "sha512": "66bf21f7deed808a742c5762edefc43e410c53be71ebb89e2f0da9e8d5949d059727e8832a5c9cf32ac878690326e4c167950e69b41356c4234786a0aec039e7",
          "sha256": "f316993da05fa94e72730e3d4efe6895ad30df46d7fe0ba376cafc6d215ad92d",
          "sha1": "736d12a9764428a20f686645df6a1338a5096f00",
          "md5": "daf1342d1aec3fe31873f429b0c1f2a5"
        }
      ]
    }
  ]
}
