{
  "formatVersion": "1.1",
  "component": {
    "group": "me.earzuchan.sakiko",
    "module": "launcher-android",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "launcher-android-0.0.1.aar",
          "url": "launcher-android-0.0.1.aar",
          "size": 6685,
          "sha512": "8b89246f8fbcae36539e3debdfc273dbe4fe2742400b4426d8bb033fde574e7a030a0a2654c2024e23d3241a0991ab5f2122e702e1050a61d29d07a5922d0648",
          "sha256": "ff8b410fda812f6604df678d6dc7e4e64e1cd320adecbd3f5b1418cdfe656f5c",
          "sha1": "cd25344ed0ab760bc851d108ab8e9055422390d1",
          "md5": "3bcaae55c53934b8d6336ceffdcaef7a"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "me.earzuchan.sakiko",
          "module": "core-android",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "org.luckypray",
          "module": "dexkit",
          "version": {
            "requires": "2.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "launcher-android-0.0.1.aar",
          "url": "launcher-android-0.0.1.aar",
          "size": 6685,
          "sha512": "8b89246f8fbcae36539e3debdfc273dbe4fe2742400b4426d8bb033fde574e7a030a0a2654c2024e23d3241a0991ab5f2122e702e1050a61d29d07a5922d0648",
          "sha256": "ff8b410fda812f6604df678d6dc7e4e64e1cd320adecbd3f5b1418cdfe656f5c",
          "sha1": "cd25344ed0ab760bc851d108ab8e9055422390d1",
          "md5": "3bcaae55c53934b8d6336ceffdcaef7a"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "launcher-android-0.0.1-sources.jar",
          "url": "launcher-android-0.0.1-sources.jar",
          "size": 5232,
          "sha512": "90a652c9a99fe7b8e47b9246f44aed1e69e6e181c903b967ae28c5cea19002f7f2a78dbe5e032f7ab53057eafe3b80366ddf4ab8e768bf72afdd0d24899fde67",
          "sha256": "8c838ce5ea83d91cb0871529400e5d21567b1a672715593871f5f9cacfa93e3c",
          "sha1": "7eba68a39c5789d3dcf545ab6d9c6720e7474f29",
          "md5": "86a4086ed5d185a9676eecaecd07e843"
        }
      ]
    }
  ]
}
