{
  "formatVersion": "1.1",
  "component": {
    "group": "me.earzuchan.hiro",
    "module": "compose",
    "version": "1.1.0-alpha-cmp1.11.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.earzuchan.hiro",
          "module": "skia",
          "version": {
            "requires": "1.1.0-alpha-cmp1.11.1"
          }
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent",
          "version": {
            "requires": "1.0.1"
          },
          "excludes": [
            {
              "group": "androidx.compose.runtime",
              "module": "*"
            },
            {
              "group": "org.jetbrains.compose.runtime",
              "module": "*"
            },
            {
              "group": "androidx.collection",
              "module": "*"
            }
          ]
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-compose",
          "version": {
            "requires": "1.4.0"
          },
          "excludes": [
            {
              "group": "androidx.compose.runtime",
              "module": "*"
            },
            {
              "group": "org.jetbrains.compose.runtime",
              "module": "*"
            },
            {
              "group": "androidx.collection",
              "module": "*"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.4"
          },
          "excludes": [
            {
              "group": "androidx.compose.runtime",
              "module": "*"
            },
            {
              "group": "org.jetbrains.compose.runtime",
              "module": "*"
            },
            {
              "group": "androidx.collection",
              "module": "*"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.9.4"
          },
          "excludes": [
            {
              "group": "androidx.compose.runtime",
              "module": "*"
            },
            {
              "group": "org.jetbrains.compose.runtime",
              "module": "*"
            },
            {
              "group": "androidx.collection",
              "module": "*"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.9.4"
          },
          "excludes": [
            {
              "group": "androidx.compose.runtime",
              "module": "*"
            },
            {
              "group": "org.jetbrains.compose.runtime",
              "module": "*"
            },
            {
              "group": "androidx.collection",
              "module": "*"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-jvm",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection-jvm",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "compose-1.1.0-alpha-cmp1.11.1.aar",
          "url": "compose-1.1.0-alpha-cmp1.11.1.aar",
          "size": 11513712,
          "sha512": "3f7e6c78af454200f56b1fe10ef2c408a54df5d59adb031508dc78914a67e457ff5e62d02fe89efb24694f53c27680778a3ce9f6873f35cf4995ebd82d5aeb87",
          "sha256": "b9787a155164b70e18b328b90b29449f6d4091f885f7df455d84f8b830cefeab",
          "sha1": "8f599d5e9cc65499b3003c2fd2abbf4671a02e8b",
          "md5": "77024955ca3212d09ddc50c8cf783b54"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu-jvm",
          "version": {
            "requires": "0.28.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "me.earzuchan.hiro",
          "module": "skia",
          "version": {
            "requires": "1.1.0-alpha-cmp1.11.1"
          }
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent",
          "version": {
            "requires": "1.0.1"
          },
          "excludes": [
            {
              "group": "androidx.compose.runtime",
              "module": "*"
            },
            {
              "group": "org.jetbrains.compose.runtime",
              "module": "*"
            },
            {
              "group": "androidx.collection",
              "module": "*"
            }
          ]
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-compose",
          "version": {
            "requires": "1.4.0"
          },
          "excludes": [
            {
              "group": "androidx.compose.runtime",
              "module": "*"
            },
            {
              "group": "org.jetbrains.compose.runtime",
              "module": "*"
            },
            {
              "group": "androidx.collection",
              "module": "*"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.4"
          },
          "excludes": [
            {
              "group": "androidx.compose.runtime",
              "module": "*"
            },
            {
              "group": "org.jetbrains.compose.runtime",
              "module": "*"
            },
            {
              "group": "androidx.collection",
              "module": "*"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.9.4"
          },
          "excludes": [
            {
              "group": "androidx.compose.runtime",
              "module": "*"
            },
            {
              "group": "org.jetbrains.compose.runtime",
              "module": "*"
            },
            {
              "group": "androidx.collection",
              "module": "*"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.9.4"
          },
          "excludes": [
            {
              "group": "androidx.compose.runtime",
              "module": "*"
            },
            {
              "group": "org.jetbrains.compose.runtime",
              "module": "*"
            },
            {
              "group": "androidx.collection",
              "module": "*"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-jvm",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection-jvm",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "compose-1.1.0-alpha-cmp1.11.1.aar",
          "url": "compose-1.1.0-alpha-cmp1.11.1.aar",
          "size": 11513712,
          "sha512": "3f7e6c78af454200f56b1fe10ef2c408a54df5d59adb031508dc78914a67e457ff5e62d02fe89efb24694f53c27680778a3ce9f6873f35cf4995ebd82d5aeb87",
          "sha256": "b9787a155164b70e18b328b90b29449f6d4091f885f7df455d84f8b830cefeab",
          "sha1": "8f599d5e9cc65499b3003c2fd2abbf4671a02e8b",
          "md5": "77024955ca3212d09ddc50c8cf783b54"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compose-1.1.0-alpha-cmp1.11.1-sources.jar",
          "url": "compose-1.1.0-alpha-cmp1.11.1-sources.jar",
          "size": 19909,
          "sha512": "37b03dbcbf56f5ed1f2b92f0819bba55a2ba63e05f17c4d20d2c70b1d92c4a2c9dfad3fef03f4ef341f409fa106413402c4a24620f4854daed0935d9f0173f57",
          "sha256": "7270164e25b8d08333555a8c26ad13eb4e190bb8950bff9fff58ae608f74b353",
          "sha1": "70ce7283e0e773a849d9838bcab729a3e4f144f7",
          "md5": "928b4a7c63784a88ae8df1423d0eabc6"
        }
      ]
    }
  ]
}
