{
  "formatVersion": "1.1",
  "component": {
    "group": "me.earzuchan.hiro",
    "module": "compose",
    "version": "1.2.0-alpha-cmp1.11.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.earzuchan.hiro",
          "module": "skia",
          "version": {
            "requires": "1.2.0-alpha-cmp1.11.1"
          }
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent",
          "version": {
            "requires": "1.0.1"
          },
          "excludes": [
            {
              "group": "androidx.compose.runtime",
              "module": "*"
            },
            {
              "group": "org.jetbrains.compose.runtime",
              "module": "*"
            },
            {
              "group": "androidx.collection",
              "module": "*"
            }
          ]
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-compose",
          "version": {
            "requires": "1.4.0"
          },
          "excludes": [
            {
              "group": "androidx.compose.runtime",
              "module": "*"
            },
            {
              "group": "org.jetbrains.compose.runtime",
              "module": "*"
            },
            {
              "group": "androidx.collection",
              "module": "*"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.4"
          },
          "excludes": [
            {
              "group": "androidx.compose.runtime",
              "module": "*"
            },
            {
              "group": "org.jetbrains.compose.runtime",
              "module": "*"
            },
            {
              "group": "androidx.collection",
              "module": "*"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.9.4"
          },
          "excludes": [
            {
              "group": "androidx.compose.runtime",
              "module": "*"
            },
            {
              "group": "org.jetbrains.compose.runtime",
              "module": "*"
            },
            {
              "group": "androidx.collection",
              "module": "*"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.9.4"
          },
          "excludes": [
            {
              "group": "androidx.compose.runtime",
              "module": "*"
            },
            {
              "group": "org.jetbrains.compose.runtime",
              "module": "*"
            },
            {
              "group": "androidx.collection",
              "module": "*"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-jvm",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection-jvm",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "compose-1.2.0-alpha-cmp1.11.1.aar",
          "url": "compose-1.2.0-alpha-cmp1.11.1.aar",
          "size": 11513700,
          "sha512": "bf2b8a51cf6d1d37d8f0e37ff8660675e104774a532436df3a15dff57b5fe58a0816f844d3544cf8a0ccee241020504e75920d53facdac412220afce0f72083e",
          "sha256": "7500693aa3272f2c92467701a1349497937bd723fbf58248717641d7a0da98b1",
          "sha1": "9e8045060587955907ee7ce2d4c990f3d4558124",
          "md5": "221690fc413b0ecabc44e57d38ff5731"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu-jvm",
          "version": {
            "requires": "0.28.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "me.earzuchan.hiro",
          "module": "skia",
          "version": {
            "requires": "1.2.0-alpha-cmp1.11.1"
          }
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent",
          "version": {
            "requires": "1.0.1"
          },
          "excludes": [
            {
              "group": "androidx.compose.runtime",
              "module": "*"
            },
            {
              "group": "org.jetbrains.compose.runtime",
              "module": "*"
            },
            {
              "group": "androidx.collection",
              "module": "*"
            }
          ]
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-compose",
          "version": {
            "requires": "1.4.0"
          },
          "excludes": [
            {
              "group": "androidx.compose.runtime",
              "module": "*"
            },
            {
              "group": "org.jetbrains.compose.runtime",
              "module": "*"
            },
            {
              "group": "androidx.collection",
              "module": "*"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.4"
          },
          "excludes": [
            {
              "group": "androidx.compose.runtime",
              "module": "*"
            },
            {
              "group": "org.jetbrains.compose.runtime",
              "module": "*"
            },
            {
              "group": "androidx.collection",
              "module": "*"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.9.4"
          },
          "excludes": [
            {
              "group": "androidx.compose.runtime",
              "module": "*"
            },
            {
              "group": "org.jetbrains.compose.runtime",
              "module": "*"
            },
            {
              "group": "androidx.collection",
              "module": "*"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.9.4"
          },
          "excludes": [
            {
              "group": "androidx.compose.runtime",
              "module": "*"
            },
            {
              "group": "org.jetbrains.compose.runtime",
              "module": "*"
            },
            {
              "group": "androidx.collection",
              "module": "*"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-jvm",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection-jvm",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "compose-1.2.0-alpha-cmp1.11.1.aar",
          "url": "compose-1.2.0-alpha-cmp1.11.1.aar",
          "size": 11513700,
          "sha512": "bf2b8a51cf6d1d37d8f0e37ff8660675e104774a532436df3a15dff57b5fe58a0816f844d3544cf8a0ccee241020504e75920d53facdac412220afce0f72083e",
          "sha256": "7500693aa3272f2c92467701a1349497937bd723fbf58248717641d7a0da98b1",
          "sha1": "9e8045060587955907ee7ce2d4c990f3d4558124",
          "md5": "221690fc413b0ecabc44e57d38ff5731"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compose-1.2.0-alpha-cmp1.11.1-sources.jar",
          "url": "compose-1.2.0-alpha-cmp1.11.1-sources.jar",
          "size": 19909,
          "sha512": "37b03dbcbf56f5ed1f2b92f0819bba55a2ba63e05f17c4d20d2c70b1d92c4a2c9dfad3fef03f4ef341f409fa106413402c4a24620f4854daed0935d9f0173f57",
          "sha256": "7270164e25b8d08333555a8c26ad13eb4e190bb8950bff9fff58ae608f74b353",
          "sha1": "70ce7283e0e773a849d9838bcab729a3e4f144f7",
          "md5": "928b4a7c63784a88ae8df1423d0eabc6"
        }
      ]
    }
  ]
}
