{
  "formatVersion": "1.1",
  "component": {
    "group": "lib.fetchmoodle",
    "module": "core",
    "version": "2026.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "com.fleeksoft.ksoup",
          "module": "ksoup",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "FetchMoodle-metadata-2026.2.4.jar",
          "url": "core-2026.2.4.jar",
          "size": 10246,
          "sha512": "be8d9674d87e48472c83ef103c9752cd4d07d0d9770d2944a4d2ca4f42fe49d06a57244ba407f947112cb078696e3180a391b8c6927cdc1aeb8d0e5e7ff6804a",
          "sha256": "71e3603e0190a10651348fc8994a419f6674831be1b8987179becce8f362ba63",
          "sha1": "5f0e13a54615ea226d8f2063282ca8643156643b",
          "md5": "599c2212e32072a0edcb8c81995be7d4"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "FetchMoodle-kotlin-2026.2.4-sources.jar",
          "url": "core-2026.2.4-sources.jar",
          "size": 11539,
          "sha512": "80aa9e1e3e0930be0e9fa6fe9604d701565b6fb49cd41909bdb3c72150e40b515b46e85edba2171a22af056ee0fcf10ef09e794c08ca6845a18e1e44c1b9417e",
          "sha256": "dd6b6e929a52cc715dc8e142e4df3c17c88f99c2597f60da0216ea578ef4cfc4",
          "sha1": "8f2871e95007363f734a6cece4f8a1c97c019361",
          "md5": "60399a724f00ada25bc64cb8ab8d0efd"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../FetchMoodle-iosarm64/2026.2.4/FetchMoodle-iosarm64-2026.2.4.module",
        "group": "lib.fetchmoodle",
        "module": "FetchMoodle-iosarm64",
        "version": "2026.2.4"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../FetchMoodle-iosarm64/2026.2.4/FetchMoodle-iosarm64-2026.2.4.module",
        "group": "lib.fetchmoodle",
        "module": "FetchMoodle-iosarm64",
        "version": "2026.2.4"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../FetchMoodle-iosarm64/2026.2.4/FetchMoodle-iosarm64-2026.2.4.module",
        "group": "lib.fetchmoodle",
        "module": "FetchMoodle-iosarm64",
        "version": "2026.2.4"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../FetchMoodle-iossimulatorarm64/2026.2.4/FetchMoodle-iossimulatorarm64-2026.2.4.module",
        "group": "lib.fetchmoodle",
        "module": "FetchMoodle-iossimulatorarm64",
        "version": "2026.2.4"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../FetchMoodle-iossimulatorarm64/2026.2.4/FetchMoodle-iossimulatorarm64-2026.2.4.module",
        "group": "lib.fetchmoodle",
        "module": "FetchMoodle-iossimulatorarm64",
        "version": "2026.2.4"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../FetchMoodle-iossimulatorarm64/2026.2.4/FetchMoodle-iossimulatorarm64-2026.2.4.module",
        "group": "lib.fetchmoodle",
        "module": "FetchMoodle-iossimulatorarm64",
        "version": "2026.2.4"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../FetchMoodle-iosx64/2026.2.4/FetchMoodle-iosx64-2026.2.4.module",
        "group": "lib.fetchmoodle",
        "module": "FetchMoodle-iosx64",
        "version": "2026.2.4"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../FetchMoodle-iosx64/2026.2.4/FetchMoodle-iosx64-2026.2.4.module",
        "group": "lib.fetchmoodle",
        "module": "FetchMoodle-iosx64",
        "version": "2026.2.4"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../FetchMoodle-iosx64/2026.2.4/FetchMoodle-iosx64-2026.2.4.module",
        "group": "lib.fetchmoodle",
        "module": "FetchMoodle-iosx64",
        "version": "2026.2.4"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../FetchMoodle-jvm/2026.2.4/FetchMoodle-jvm-2026.2.4.module",
        "group": "lib.fetchmoodle",
        "module": "FetchMoodle-jvm",
        "version": "2026.2.4"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../FetchMoodle-jvm/2026.2.4/FetchMoodle-jvm-2026.2.4.module",
        "group": "lib.fetchmoodle",
        "module": "FetchMoodle-jvm",
        "version": "2026.2.4"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../FetchMoodle-jvm/2026.2.4/FetchMoodle-jvm-2026.2.4.module",
        "group": "lib.fetchmoodle",
        "module": "FetchMoodle-jvm",
        "version": "2026.2.4"
      }
    }
  ]
}
