{
  "formatVersion": "1.1",
  "component": {
    "group": "me.earzuchan.hiro",
    "module": "material3",
    "version": "1.0.1-alpha-cmp1.11.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.earzuchan.hiro",
          "module": "compose",
          "version": {
            "requires": "1.0.1-alpha-cmp1.11.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "material3-1.0.1-alpha-cmp1.11.1.aar",
          "url": "material3-1.0.1-alpha-cmp1.11.1.aar",
          "size": 4472841,
          "sha512": "a50d05f1b33487b5e2c3d9e934ff3f616f907174f962e2a3f499db7e118402e2a9e4bea298245ad94bd8e541cefc0d739ba0abe9de7c43591560554e22bf0cd7",
          "sha256": "97c3ee49d407bb8ca738beb45878093e14e777fa11358e1719200e57e7197f71",
          "sha1": "a0fb6f11b11396c4a0b6281edafcb6e62607738d",
          "md5": "f51c7f78487ea042de628a2d008dae4d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.earzuchan.hiro",
          "module": "compose",
          "version": {
            "requires": "1.0.1-alpha-cmp1.11.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "material3-1.0.1-alpha-cmp1.11.1.aar",
          "url": "material3-1.0.1-alpha-cmp1.11.1.aar",
          "size": 4472841,
          "sha512": "a50d05f1b33487b5e2c3d9e934ff3f616f907174f962e2a3f499db7e118402e2a9e4bea298245ad94bd8e541cefc0d739ba0abe9de7c43591560554e22bf0cd7",
          "sha256": "97c3ee49d407bb8ca738beb45878093e14e777fa11358e1719200e57e7197f71",
          "sha1": "a0fb6f11b11396c4a0b6281edafcb6e62607738d",
          "md5": "f51c7f78487ea042de628a2d008dae4d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "material3-1.0.1-alpha-cmp1.11.1-sources.jar",
          "url": "material3-1.0.1-alpha-cmp1.11.1-sources.jar",
          "size": 9339,
          "sha512": "ab2b9ee24995ca1367d55a8fdc22768e29d94517d3f8e569871c94613ee9750f702c31d1aad1be9655760bf99dd22e148dac40b887d4bf2439affa0f7ed8504a",
          "sha256": "c65cd67eeeba5f4e5c5720676ae98ce14f555bbf3ab847a8823a98d4e227a3ac",
          "sha1": "4fc89ec900d79792939941db37dc7eb69cb83f86",
          "md5": "a63168065174a959acf01c5e098e686b"
        }
      ]
    }
  ]
}
