{
  "formatVersion": "1.1",
  "component": {
    "group": "me.earzuchan.hiro",
    "module": "compose",
    "version": "1.6.6-alpha-cmp1.11.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.earzuchan.hiro",
          "module": "skia",
          "version": {
            "requires": "1.6.6-alpha-cmp1.11.1"
          }
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent",
          "version": {
            "requires": "1.1.2"
          },
          "excludes": [
            {
              "group": "androidx.annotation",
              "module": "*"
            },
            {
              "group": "androidx.compose.runtime",
              "module": "*"
            },
            {
              "group": "org.jetbrains.compose.runtime",
              "module": "*"
            },
            {
              "group": "androidx.lifecycle",
              "module": "lifecycle-viewmodel-navigation3"
            },
            {
              "group": "androidx.savedstate",
              "module": "savedstate-compose"
            },
            {
              "group": "androidx.compose.ui",
              "module": "*"
            },
            {
              "group": "androidx.lifecycle",
              "module": "lifecycle-viewmodel-compose"
            },
            {
              "group": "androidx.collection",
              "module": "*"
            },
            {
              "group": "androidx.lifecycle",
              "module": "lifecycle-runtime-compose"
            }
          ]
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-compose",
          "version": {
            "requires": "1.1.2"
          },
          "excludes": [
            {
              "group": "androidx.annotation",
              "module": "*"
            },
            {
              "group": "androidx.compose.runtime",
              "module": "*"
            },
            {
              "group": "org.jetbrains.compose.runtime",
              "module": "*"
            },
            {
              "group": "androidx.lifecycle",
              "module": "lifecycle-viewmodel-navigation3"
            },
            {
              "group": "androidx.savedstate",
              "module": "savedstate-compose"
            },
            {
              "group": "androidx.compose.ui",
              "module": "*"
            },
            {
              "group": "androidx.lifecycle",
              "module": "lifecycle-viewmodel-compose"
            },
            {
              "group": "androidx.collection",
              "module": "*"
            },
            {
              "group": "androidx.lifecycle",
              "module": "lifecycle-runtime-compose"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-jvm",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection-jvm",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.4.0"
          },
          "excludes": [
            {
              "group": "androidx.compose.runtime",
              "module": "*"
            },
            {
              "group": "org.jetbrains.compose.runtime",
              "module": "*"
            },
            {
              "group": "androidx.lifecycle",
              "module": "lifecycle-viewmodel-navigation3"
            },
            {
              "group": "androidx.savedstate",
              "module": "savedstate-compose"
            },
            {
              "group": "androidx.compose.ui",
              "module": "*"
            },
            {
              "group": "androidx.lifecycle",
              "module": "lifecycle-viewmodel-compose"
            },
            {
              "group": "androidx.lifecycle",
              "module": "lifecycle-runtime-compose"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.10.0"
          },
          "excludes": [
            {
              "group": "androidx.compose.runtime",
              "module": "*"
            },
            {
              "group": "org.jetbrains.compose.runtime",
              "module": "*"
            },
            {
              "group": "androidx.lifecycle",
              "module": "lifecycle-viewmodel-navigation3"
            },
            {
              "group": "androidx.savedstate",
              "module": "savedstate-compose"
            },
            {
              "group": "androidx.compose.ui",
              "module": "*"
            },
            {
              "group": "androidx.lifecycle",
              "module": "lifecycle-viewmodel-compose"
            },
            {
              "group": "androidx.lifecycle",
              "module": "lifecycle-runtime-compose"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.10.0"
          },
          "excludes": [
            {
              "group": "androidx.compose.runtime",
              "module": "*"
            },
            {
              "group": "org.jetbrains.compose.runtime",
              "module": "*"
            },
            {
              "group": "androidx.lifecycle",
              "module": "lifecycle-viewmodel-navigation3"
            },
            {
              "group": "androidx.savedstate",
              "module": "savedstate-compose"
            },
            {
              "group": "androidx.compose.ui",
              "module": "*"
            },
            {
              "group": "androidx.lifecycle",
              "module": "lifecycle-viewmodel-compose"
            },
            {
              "group": "androidx.lifecycle",
              "module": "lifecycle-runtime-compose"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.10.0"
          },
          "excludes": [
            {
              "group": "androidx.compose.runtime",
              "module": "*"
            },
            {
              "group": "org.jetbrains.compose.runtime",
              "module": "*"
            },
            {
              "group": "androidx.lifecycle",
              "module": "lifecycle-viewmodel-navigation3"
            },
            {
              "group": "androidx.savedstate",
              "module": "savedstate-compose"
            },
            {
              "group": "androidx.compose.ui",
              "module": "*"
            },
            {
              "group": "androidx.lifecycle",
              "module": "lifecycle-viewmodel-compose"
            },
            {
              "group": "androidx.lifecycle",
              "module": "lifecycle-runtime-compose"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "compose-1.6.6-alpha-cmp1.11.1.aar",
          "url": "compose-1.6.6-alpha-cmp1.11.1.aar",
          "size": 11761544,
          "sha512": "238005134cd2a1f66cfde50ceee681d710ad386f7ac7aa18827c84b08c10caa4218e06a7ab856203edc956b8c585aec4028cc83fb6ebea9a74e8f2c41d5576b5",
          "sha256": "3cb844fb8bbaee0fe15cea1cfe9fad77689bd8c9b7b53f055c8f2202b156af2f",
          "sha1": "65ac168215624d4fc4154adb60cd57b3794a3f77",
          "md5": "2a27cc945e3a1e37a59cf9823f1ac06f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu-jvm",
          "version": {
            "requires": "0.28.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.12.4"
          },
          "excludes": [
            {
              "group": "androidx.compose.runtime",
              "module": "*"
            },
            {
              "group": "org.jetbrains.compose.runtime",
              "module": "*"
            },
            {
              "group": "androidx.lifecycle",
              "module": "lifecycle-viewmodel-navigation3"
            },
            {
              "group": "androidx.savedstate",
              "module": "savedstate-compose"
            },
            {
              "group": "androidx.compose.ui",
              "module": "*"
            },
            {
              "group": "androidx.lifecycle",
              "module": "lifecycle-viewmodel-compose"
            },
            {
              "group": "androidx.lifecycle",
              "module": "lifecycle-runtime-compose"
            }
          ]
        },
        {
          "group": "me.earzuchan.hiro",
          "module": "skia",
          "version": {
            "requires": "1.6.6-alpha-cmp1.11.1"
          }
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent",
          "version": {
            "requires": "1.1.2"
          },
          "excludes": [
            {
              "group": "androidx.annotation",
              "module": "*"
            },
            {
              "group": "androidx.compose.runtime",
              "module": "*"
            },
            {
              "group": "org.jetbrains.compose.runtime",
              "module": "*"
            },
            {
              "group": "androidx.lifecycle",
              "module": "lifecycle-viewmodel-navigation3"
            },
            {
              "group": "androidx.savedstate",
              "module": "savedstate-compose"
            },
            {
              "group": "androidx.compose.ui",
              "module": "*"
            },
            {
              "group": "androidx.lifecycle",
              "module": "lifecycle-viewmodel-compose"
            },
            {
              "group": "androidx.collection",
              "module": "*"
            },
            {
              "group": "androidx.lifecycle",
              "module": "lifecycle-runtime-compose"
            }
          ]
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-compose",
          "version": {
            "requires": "1.1.2"
          },
          "excludes": [
            {
              "group": "androidx.annotation",
              "module": "*"
            },
            {
              "group": "androidx.compose.runtime",
              "module": "*"
            },
            {
              "group": "org.jetbrains.compose.runtime",
              "module": "*"
            },
            {
              "group": "androidx.lifecycle",
              "module": "lifecycle-viewmodel-navigation3"
            },
            {
              "group": "androidx.savedstate",
              "module": "savedstate-compose"
            },
            {
              "group": "androidx.compose.ui",
              "module": "*"
            },
            {
              "group": "androidx.lifecycle",
              "module": "lifecycle-viewmodel-compose"
            },
            {
              "group": "androidx.collection",
              "module": "*"
            },
            {
              "group": "androidx.lifecycle",
              "module": "lifecycle-runtime-compose"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-jvm",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection-jvm",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.4.0"
          },
          "excludes": [
            {
              "group": "androidx.compose.runtime",
              "module": "*"
            },
            {
              "group": "org.jetbrains.compose.runtime",
              "module": "*"
            },
            {
              "group": "androidx.lifecycle",
              "module": "lifecycle-viewmodel-navigation3"
            },
            {
              "group": "androidx.savedstate",
              "module": "savedstate-compose"
            },
            {
              "group": "androidx.compose.ui",
              "module": "*"
            },
            {
              "group": "androidx.lifecycle",
              "module": "lifecycle-viewmodel-compose"
            },
            {
              "group": "androidx.lifecycle",
              "module": "lifecycle-runtime-compose"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.10.0"
          },
          "excludes": [
            {
              "group": "androidx.compose.runtime",
              "module": "*"
            },
            {
              "group": "org.jetbrains.compose.runtime",
              "module": "*"
            },
            {
              "group": "androidx.lifecycle",
              "module": "lifecycle-viewmodel-navigation3"
            },
            {
              "group": "androidx.savedstate",
              "module": "savedstate-compose"
            },
            {
              "group": "androidx.compose.ui",
              "module": "*"
            },
            {
              "group": "androidx.lifecycle",
              "module": "lifecycle-viewmodel-compose"
            },
            {
              "group": "androidx.lifecycle",
              "module": "lifecycle-runtime-compose"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.10.0"
          },
          "excludes": [
            {
              "group": "androidx.compose.runtime",
              "module": "*"
            },
            {
              "group": "org.jetbrains.compose.runtime",
              "module": "*"
            },
            {
              "group": "androidx.lifecycle",
              "module": "lifecycle-viewmodel-navigation3"
            },
            {
              "group": "androidx.savedstate",
              "module": "savedstate-compose"
            },
            {
              "group": "androidx.compose.ui",
              "module": "*"
            },
            {
              "group": "androidx.lifecycle",
              "module": "lifecycle-viewmodel-compose"
            },
            {
              "group": "androidx.lifecycle",
              "module": "lifecycle-runtime-compose"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.10.0"
          },
          "excludes": [
            {
              "group": "androidx.compose.runtime",
              "module": "*"
            },
            {
              "group": "org.jetbrains.compose.runtime",
              "module": "*"
            },
            {
              "group": "androidx.lifecycle",
              "module": "lifecycle-viewmodel-navigation3"
            },
            {
              "group": "androidx.savedstate",
              "module": "savedstate-compose"
            },
            {
              "group": "androidx.compose.ui",
              "module": "*"
            },
            {
              "group": "androidx.lifecycle",
              "module": "lifecycle-viewmodel-compose"
            },
            {
              "group": "androidx.lifecycle",
              "module": "lifecycle-runtime-compose"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "compose-1.6.6-alpha-cmp1.11.1.aar",
          "url": "compose-1.6.6-alpha-cmp1.11.1.aar",
          "size": 11761544,
          "sha512": "238005134cd2a1f66cfde50ceee681d710ad386f7ac7aa18827c84b08c10caa4218e06a7ab856203edc956b8c585aec4028cc83fb6ebea9a74e8f2c41d5576b5",
          "sha256": "3cb844fb8bbaee0fe15cea1cfe9fad77689bd8c9b7b53f055c8f2202b156af2f",
          "sha1": "65ac168215624d4fc4154adb60cd57b3794a3f77",
          "md5": "2a27cc945e3a1e37a59cf9823f1ac06f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compose-1.6.6-alpha-cmp1.11.1-sources.jar",
          "url": "compose-1.6.6-alpha-cmp1.11.1-sources.jar",
          "size": 53517,
          "sha512": "0eeb572c4710fb787291e7b5bb348b60db8bba6bb4854f64869715c4a5b40f85065a17cd3b1e034b576c893604eecd80f6af9d9abcdcd465c222ba63f48d6313",
          "sha256": "cb00d23115c8843f8cd8d7e365c2abf6ae66e93b66d19dad8f0fb3882bd14854",
          "sha1": "834e91f29293072197f5af48aa4194a24d861da2",
          "md5": "9df2acc919f5f3f654541a8213209569"
        }
      ]
    }
  ]
}
