{
  "formatVersion": "1.1",
  "component": {
    "url": "../../FetchMoodle/2026.2.2/FetchMoodle-2026.2.2.module",
    "group": "lib.fetchmoodle",
    "module": "FetchMoodle",
    "version": "2026.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.fleeksoft.ksoup",
          "module": "ksoup",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "FetchMoodle-iosSimulatorArm64Main-2026.2.2.klib",
          "url": "FetchMoodle-iossimulatorarm64-2026.2.2.klib",
          "size": 132903,
          "sha512": "a4b32760529d5c5f85a2d93cc9f498c81964b1a2e6744828df33df826ba707fc55a5b4ebf590d971a25a77791fc9106ed1fb4aee04d87504d5b7b061dab00272",
          "sha256": "2aeef8edd4e16e69c90987f397c962ca1118940e476ba33df03b759f8090821f",
          "sha1": "cd905eb4a0eb96bc31bceb39b483d076740f0ed7",
          "md5": "fcf71748e6b8dba2657490ee519e01a1"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "FetchMoodle-iossimulatorarm64-2026.2.2-sources.jar",
          "url": "FetchMoodle-iossimulatorarm64-2026.2.2-sources.jar",
          "size": 10947,
          "sha512": "72e1a4425544a1e0e8a53bb929dcf6b542c52cc51c2291b3222209b8a498ca7c2ebb2d98f76cf62e7279b07f7e3f9e34e641c4c2d404537633646f118c327b58",
          "sha256": "5ac21483c57f132efcd273bdaed36b6a3b152ed04740598b7146091f350c1296",
          "sha1": "31d9e4411c6b942b415673db863f4dd23ef08e44",
          "md5": "4dbcc660706c0a38eb8b9430556f3728"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.fleeksoft.ksoup",
          "module": "ksoup",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "FetchMoodle-iossimulatorarm64-2026.2.2-metadata.jar",
          "url": "FetchMoodle-iossimulatorarm64-2026.2.2-metadata.jar",
          "size": 261,
          "sha512": "896875749ef84d352b96960897bc74fb06837ef755ff513324a14797cf7167653866259a2a4b956bfaa877919df0f852a151e2facfa47d4176c87f25b18b8f30",
          "sha256": "a9adc98af0ab0ff25b1e3451c031bc3b5e85651400425a4f6fe371c9d67c8a34",
          "sha1": "05aabf8ca38836c18a16b970c9e29adfc85623ae",
          "md5": "199c59242a6e04221368469f495ce659"
        }
      ]
    }
  ]
}
