{
  "formatVersion": "1.1",
  "component": {
    "group": "me.earzuchan.hiro",
    "module": "material3",
    "version": "1.1.0-alpha-cmp1.11.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.earzuchan.hiro",
          "module": "compose",
          "version": {
            "requires": "1.1.0-alpha-cmp1.11.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "material3-1.1.0-alpha-cmp1.11.1.aar",
          "url": "material3-1.1.0-alpha-cmp1.11.1.aar",
          "size": 4474267,
          "sha512": "24d24605a89c2aa125bc684029c2e5316157f748faeff77a8c64a190e68657266ccb6de3017c3b3fdc4c6e55d2f152af5662d09b343a11309e9dc035646199a4",
          "sha256": "3cf73725359f8429de454707469d7beaf4a7acd8047f6a4ba0a5f1d40a976964",
          "sha1": "b50ee1058246ec9ae66dccb0482228a42b9906b8",
          "md5": "11c11ab5db4f60cea11c185c7afe9b28"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.earzuchan.hiro",
          "module": "compose",
          "version": {
            "requires": "1.1.0-alpha-cmp1.11.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "material3-1.1.0-alpha-cmp1.11.1.aar",
          "url": "material3-1.1.0-alpha-cmp1.11.1.aar",
          "size": 4474267,
          "sha512": "24d24605a89c2aa125bc684029c2e5316157f748faeff77a8c64a190e68657266ccb6de3017c3b3fdc4c6e55d2f152af5662d09b343a11309e9dc035646199a4",
          "sha256": "3cf73725359f8429de454707469d7beaf4a7acd8047f6a4ba0a5f1d40a976964",
          "sha1": "b50ee1058246ec9ae66dccb0482228a42b9906b8",
          "md5": "11c11ab5db4f60cea11c185c7afe9b28"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "material3-1.1.0-alpha-cmp1.11.1-sources.jar",
          "url": "material3-1.1.0-alpha-cmp1.11.1-sources.jar",
          "size": 9339,
          "sha512": "ab2b9ee24995ca1367d55a8fdc22768e29d94517d3f8e569871c94613ee9750f702c31d1aad1be9655760bf99dd22e148dac40b887d4bf2439affa0f7ed8504a",
          "sha256": "c65cd67eeeba5f4e5c5720676ae98ce14f555bbf3ab847a8823a98d4e227a3ac",
          "sha1": "4fc89ec900d79792939941db37dc7eb69cb83f86",
          "md5": "a63168065174a959acf01c5e098e686b"
        }
      ]
    }
  ]
}
