{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/2026.2.3/core-2026.2.3.module",
    "group": "lib.fetchmoodle",
    "module": "core",
    "version": "2026.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "com.fleeksoft.ksoup",
          "module": "ksoup",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "FetchMoodle-iosX64Main-2026.2.3.klib",
          "url": "FetchMoodle-iosx64-2026.2.3.klib",
          "size": 133912,
          "sha512": "30fb204d6443c913c6bbb6b6bbe2a909260bc82676689d451c420e4a12534ed68abc3965aeb9197fe61f6f81e2223110984996a7bc21624ad5199f71db0ce2d6",
          "sha256": "b25b948050674f26122647cc6c7687eb3b170a067a462d2a29dfd98532c4b086",
          "sha1": "5417d440bd25b5cf6e9fe357a42f0df92030368b",
          "md5": "db0d8e2dae8256de0c2ec49cc15c8bd2"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "FetchMoodle-iosx64-2026.2.3-sources.jar",
          "url": "FetchMoodle-iosx64-2026.2.3-sources.jar",
          "size": 11555,
          "sha512": "66bf21f7deed808a742c5762edefc43e410c53be71ebb89e2f0da9e8d5949d059727e8832a5c9cf32ac878690326e4c167950e69b41356c4234786a0aec039e7",
          "sha256": "f316993da05fa94e72730e3d4efe6895ad30df46d7fe0ba376cafc6d215ad92d",
          "sha1": "736d12a9764428a20f686645df6a1338a5096f00",
          "md5": "daf1342d1aec3fe31873f429b0c1f2a5"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "com.fleeksoft.ksoup",
          "module": "ksoup",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "FetchMoodle-iosx64-2026.2.3-metadata.jar",
          "url": "FetchMoodle-iosx64-2026.2.3-metadata.jar",
          "size": 261,
          "sha512": "b6ec95d2b5786c57b6120f46c67078811fcebe4802456a98dd5125bff7d5546c8acde5b1f001f92e188e241ee0cf490f8ff401c9d8fbd1d833ba773aeb965dd6",
          "sha256": "ef88cac838de63e158c26792805c82725a16f3acb0c1ceaaa81f07a68b8d2138",
          "sha1": "db0036b7772e0adf74d19ac6f4eadf7c75d25bac",
          "md5": "a2fe416885fb435c6fdf3689b866d903"
        }
      ]
    }
  ]
}
