{
  "formatVersion": "1.1",
  "component": {
    "group": "me.earzuchan.hiro.gradleplugin",
    "module": "hiro-gradle-plugin",
    "version": "1.2.0-alpha-cmp1.11.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "hiro-gradle-plugin-1.2.0-alpha-cmp1.11.1.jar",
          "url": "hiro-gradle-plugin-1.2.0-alpha-cmp1.11.1.jar",
          "size": 62774,
          "sha512": "e2806c30a13c12e378f8354848a08a57c66aeb3137a58b83a8fec5efb1703bc70a6c24835ff7c1b49b545e2e1b4191bac5cdc8530a5bfec4f5949eb19b1bb667",
          "sha256": "9394b393f8d93d06dc6353dd0e9695d73afdc0e3205ca23696e17b8a0e0c9f9d",
          "sha1": "abbf636ff79c49853a736330ee1c0fd3f0c5e2a7",
          "md5": "b2f504506e67f76430582919b27596cd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "hiro-gradle-plugin-1.2.0-alpha-cmp1.11.1.jar",
          "url": "hiro-gradle-plugin-1.2.0-alpha-cmp1.11.1.jar",
          "size": 62774,
          "sha512": "e2806c30a13c12e378f8354848a08a57c66aeb3137a58b83a8fec5efb1703bc70a6c24835ff7c1b49b545e2e1b4191bac5cdc8530a5bfec4f5949eb19b1bb667",
          "sha256": "9394b393f8d93d06dc6353dd0e9695d73afdc0e3205ca23696e17b8a0e0c9f9d",
          "sha1": "abbf636ff79c49853a736330ee1c0fd3f0c5e2a7",
          "md5": "b2f504506e67f76430582919b27596cd"
        }
      ]
    }
  ]
}
