{
  "formatVersion": "1.1",
  "component": {
    "url": "../../FetchMoodle/2026.2.2/FetchMoodle-2026.2.2.module",
    "group": "lib.fetchmoodle",
    "module": "FetchMoodle",
    "version": "2026.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.fleeksoft.ksoup",
          "module": "ksoup",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "FetchMoodle-iosX64Main-2026.2.2.klib",
          "url": "FetchMoodle-iosx64-2026.2.2.klib",
          "size": 132824,
          "sha512": "9349b1c34c7007eac8f8827e58f511ecf86ea46b2df5900996c4133779000ff2555c75d1c0482e6935a1a54fc7f4fe79f2761f237ad50d7cdeed6f19cf52fa62",
          "sha256": "0afe3c07e3ca2a1edefa39f79839cb0846b200c9fd88cb7b37e6fc803bbfa930",
          "sha1": "5af03591f72bdce4f295895fcf02314b6314045b",
          "md5": "b391de21749357749b20e244f2a9ccea"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "FetchMoodle-iosx64-2026.2.2-sources.jar",
          "url": "FetchMoodle-iosx64-2026.2.2-sources.jar",
          "size": 10947,
          "sha512": "72e1a4425544a1e0e8a53bb929dcf6b542c52cc51c2291b3222209b8a498ca7c2ebb2d98f76cf62e7279b07f7e3f9e34e641c4c2d404537633646f118c327b58",
          "sha256": "5ac21483c57f132efcd273bdaed36b6a3b152ed04740598b7146091f350c1296",
          "sha1": "31d9e4411c6b942b415673db863f4dd23ef08e44",
          "md5": "4dbcc660706c0a38eb8b9430556f3728"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.fleeksoft.ksoup",
          "module": "ksoup",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "FetchMoodle-iosx64-2026.2.2-metadata.jar",
          "url": "FetchMoodle-iosx64-2026.2.2-metadata.jar",
          "size": 261,
          "sha512": "896875749ef84d352b96960897bc74fb06837ef755ff513324a14797cf7167653866259a2a4b956bfaa877919df0f852a151e2facfa47d4176c87f25b18b8f30",
          "sha256": "a9adc98af0ab0ff25b1e3451c031bc3b5e85651400425a4f6fe371c9d67c8a34",
          "sha1": "05aabf8ca38836c18a16b970c9e29adfc85623ae",
          "md5": "199c59242a6e04221368469f495ce659"
        }
      ]
    }
  ]
}
