{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/2026.2.3/core-2026.2.3.module",
    "group": "lib.fetchmoodle",
    "module": "core",
    "version": "2026.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "com.fleeksoft.ksoup",
          "module": "ksoup",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "FetchMoodle-iosSimulatorArm64Main-2026.2.3.klib",
          "url": "FetchMoodle-iossimulatorarm64-2026.2.3.klib",
          "size": 133990,
          "sha512": "dd3a21a66e59b91598cb04fe90e090998dfc47858716237c38d039629b26b1dfd11e0e35d00fb47ca3ddbf3f67443e492cc711e2f9ca4f3624eb8ef091e98818",
          "sha256": "3c130e7ed064cddaeab9d8c1d1ac2e696b42645e139376060a2528991da713f6",
          "sha1": "d9c630c6d1c5eb86790af844a515731b0f64b455",
          "md5": "707698d1fa87a43d95a791497df01941"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "FetchMoodle-iossimulatorarm64-2026.2.3-sources.jar",
          "url": "FetchMoodle-iossimulatorarm64-2026.2.3-sources.jar",
          "size": 11555,
          "sha512": "66bf21f7deed808a742c5762edefc43e410c53be71ebb89e2f0da9e8d5949d059727e8832a5c9cf32ac878690326e4c167950e69b41356c4234786a0aec039e7",
          "sha256": "f316993da05fa94e72730e3d4efe6895ad30df46d7fe0ba376cafc6d215ad92d",
          "sha1": "736d12a9764428a20f686645df6a1338a5096f00",
          "md5": "daf1342d1aec3fe31873f429b0c1f2a5"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "com.fleeksoft.ksoup",
          "module": "ksoup",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "FetchMoodle-iossimulatorarm64-2026.2.3-metadata.jar",
          "url": "FetchMoodle-iossimulatorarm64-2026.2.3-metadata.jar",
          "size": 261,
          "sha512": "513c17535f2fa768a3c03779cd03f3f7a9c3cb6fe709b49c8183b5b8ec4d9302aa15c789df108d6b46e01208e7a3aa5f6cb917144be5201c7f79e41cb22caf80",
          "sha256": "69e35a66ed2ec5f2dc4e877c86fbb251caeec29b6c13d6c9af4ea8a055e1a7d4",
          "sha1": "b23e676bde8a7a051ebf2664892f66fc1760e3ec",
          "md5": "b433363be216058a284813c6c137fe35"
        }
      ]
    }
  ]
}
